### ISSUE TITLE
Baixar 2 novos csv's do portal ICMBio

### ISSUE THREAD

**Issue by GabrielFiletti** [GabrielFiletti/Avaliando_qualidade_dados_de_ocorrencia#1]
**Resumo das atividades:**

- Baixar novos dois arquivos do tipo csv do Portal da Biodiversidade do ICMBio.

- Seguir o tutorial: https://nbviewer.jupyter.org/github/lazaropd/desafio-1-2-005/blob/master/Instru%C3%A7%C3%B5es%20para%20abrir%20arquivo%20no%20excel.pdf

**Comment by lazaropd** [comment]
Baixei 2 novos arquivos, priorizei o tamanho para ajudar na performance. Um com 2 linhas e um com 43 linhas. Esse de 43 linhas está bem legal para ser executado no mapa, bem espalhado pelo Brasil
