### ISSUE TITLE
Implementar a nova comparação para os dados de latitude e longitude utilizando os exemplos anteriores de comparação de palavras

### ISSUE THREAD

**Issue by GabrielFiletti** [GabrielFiletti/Avaliando_qualidade_dados_de_ocorrencia#13]
**Resumo das atividades:**

- Utilizar os exemplos das aulas anteriores sobre distância de palavras para comparar os dados de latitude e longitude.

**Comment by lazaropd** [comment]
Alterados os arquivos search e visualizer, e adicionado um txt com as stopwords em portugues, o programa agora faz uma comparacao entre os 2 endereços e retorna a similaridade. O raio e a cor dos pontos são ajustados em função desta similaridade
