### ISSUE TITLE
Utilizar o Streamlit para visualização dos dados.

### ISSUE THREAD

**Issue by GabrielFiletti** [GabrielFiletti/Avaliando_qualidade_dados_de_ocorrencia#4]
**Resumo das atividades:**

- Utilizar a ferramenta Streamlit para criar uma dashboard para visualização dos dados.

- Documentar as operações realizadas para os outros membros do grupo compreenderem a utilização da ferramenta.

**Comment by lazaropd** [comment]
Subi o arquivo. A ferramenta streamlit tem um poder enorme mas ainda é bastante nova. Então carece de documentação e também de foruns especializados.
Subi uma versão funcionando com 2 cores (verde e vermelho) sendo verde quando a coordenada coincide pelo menos 2 informações com a observação. Para isso tive que plotar 2 layers, uma para cada subset.

Futuramente com mais documentação online podemos tentar features mais avançadas como por exemplo:
- usar um gradiente de cor para os pontos em função do valor de determinada coluna (ex. setColorR);
- mostrar um popup ao fazer hover em um ponto no mapa;
- plotar um map object de outra biblioteca (ipyleaflet ou folium por exemplo) - não suportado ainda

Bugs conhecidos:
- o viewport não atualiza quando o dataframe é filtrado no browser, então o zoom e a posição do mapa com os pontos podem ficar descentralizados;
